### ISSUE TITLE
[Infra] Incorrect YAML Files - validation failures

### ISSUE THREAD

**Issue by justinwilaby** [Microsoft/Recognizers-Text#1496]
Yaml validation failures - duplicate keys are found during parsing in several yaml files with some having completely different definitions. Running a simple yaml validation tool yields:
//-------------------------------------------------
### Dutch-DateTime.yaml - different definitions for same identifier
```yaml
AmDescRegex: !nestedRegex
  def: ({BaseDateTime.BaseAmDescRegex})
  references: [BaseDateTime.BaseAmDescRegex]

AmDescRegex: !simpleRegex
  def: (am\b|a\.m\.|a m\b|a\. m\.|a\.m\b|a\. m\b|a m\b)

PmDescRegex: !nestedRegex
  def: ({BaseDateTime.BasePmDescRegex})
  references: [BaseDateTime.BasePmDescRegex]

PmDescRegex: !simpleRegex
  def: (pm\b|p\.m\.|p\b|p m\b|p\. m\.|p\.m\b|p\. m\b|p m\b)

```
Also, `OclockRegex` is duplicated on lines 66 and 290
//-------------------------------------------------
### English-TimeZone.yaml
`eest` exists on lines 370 and 403
//-------------------------------------------------
### German-DateTime.yaml
`FullTextYearRegex` exists on lines 46 and 573
`DayOfMonth` also contains duplicate keys in the `entries` object
//-------------------------------------------------
### Japanese-DateTime.yaml - 2 different definitions
```yaml
DayRegex: !simpleRegex #<--- defined with an empty body

DayRegex: !simpleRegex
  def: (?<day>01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|1|2|3|4|5|6|7|8|9)日?
```
//-------------------------------------------------
### Spanish-DateTime.yaml 
BOM detected in this file which prevents parsing on some platforms.
![image](https://user-images.githubusercontent.com/2652885/54535792-85a47300-494c-11e9-801e-3a143f862364.png)
